# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: ${{ secrets.DB_password }}
  APP_DB_NAME: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Start services
        run: docker compose up -d

      - name: Run tests
        run: go test -v ./...

      - name: Build project
        run: go build -v ./...
